sudo: false

language: cpp

compiler: gcc

before_install:
  - export CXX="g++-5"
  - g++-5 --version
  - cd ~
  - rm -rf libs/
  - mkdir libs && cd libs
  - git clone https://github.com/jbeder/yaml-cpp.git
  - cd yaml-cpp && mkdir build && cd build
  - cmake ..

install:
  - cd ~/libs/yaml-cpp/build
  - make -j$(nproc)
  - export PATH=$PATH:$(pwd)

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake ..

script:
  - cd $TRAVIS_BUILD_DIR
  - cd build
  - make -j$(nproc)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-5
      - libboost1.55-dev
