sudo: false

language: cpp

compiler: gcc

before_install:
  - export cwd=$(pwd)
  - export CXX="g++-4.9"
  - gcc --version
  - mkdir added-libs && cd added-libs
  - git clone https://github.com/jbeder/yaml-cpp.git
  - cd yaml-cpp && mkdir build && cd build
  - cmake ..

install:
  - cd $cwd
  - cd added-libs/yaml-cpp
  - export PATH=$PATH:$(pwd)/include
  - cd build
  - make -j$(nproc)
  - export PATH=$PATH:$(pwd)

before_script:
  - cd $cwd
  - mkdir build && cd build
  - cmake ..

script:
  - cd $cwd
  - cd build
  - make -j$(nproc)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-4.9
      - libboost1.55-dev
