sudo: false

language: cpp

compiler: gcc

before_install:
  - export repo=$(pwd)
  - cd ~
  - export CXX="g++-4.9"
  - g++-4.9 --version
  - mkdir libs && cd libs
  - git clone https://github.com/jbeder/yaml-cpp.git
  - cd yaml-cpp && mkdir build && cd build
  - cmake ..

install:
  - cd ~/libs/yaml-cpp/build
  - make -j$(nproc)
  - export PATH=$PATH:$(pwd)

before_script:
  - cd $repo
  - mkdir build && cd build
  - cmake ..

script:
  - cd $repo
  - cd build
  - make -j$(nproc)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-4.9
      - libboost1.55-dev
